//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadManagementSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public int ID { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> LeadDate { get; set; }
        public Nullable<int> LeadType { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> TimeZone { get; set; }
        public string Location { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> LeadStatus { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string NextPlan { get; set; }
        public string IntialRequirements { get; set; }
        public Nullable<int> AssignedToUSerID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Status { get; set; }
        public Nullable<int> Created_By { get; set; }
        public string LastStatus { get; set; }
        public string LeadTime { get; set; }
    }
}
