//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadManagementSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadType
    {
        public int ID { get; set; }
        public string LeadTypeName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Status { get; set; }
        public Nullable<int> Created_By { get; set; }
    }
}
