//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadManagementSystems
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LeadCRMEntities : DbContext
    {
        public LeadCRMEntities()
            : base("name=LeadCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Role> tbl_Role { get; set; }
        public DbSet<USER> USERs { get; set; }
        public DbSet<LeadType> LeadTypes { get; set; }
        public DbSet<TimeZone> TimeZones { get; set; }
        public DbSet<Lead> Leads { get; set; }
        public DbSet<notification> notifications { get; set; }
    
        public virtual ObjectResult<sp_ReadData_Result> sp_ReadData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReadData_Result>("sp_ReadData");
        }
    
        public virtual ObjectResult<sp_readdatalead_Result> sp_readdatalead()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_readdatalead_Result>("sp_readdatalead");
        }
    }
}
